version: '3.7'

services:
  web:
    build:
      context: ./
    container_name: brolga
    volumes:
      - /var/run/docker.sock:/tmp/docker.sock:ro
      - ./src:/opt/brolga
      - ./examples:/var/docker/examples
    ports:
      - 8080:80
    environment:
      FLASK_ENV: development
