version: '3.7'

services:
  deploy:
    build:
      context: ./
    container_name: docker-deploy
    volumes:
      - ./src:/opt/deploy
      - ./examples:/var/docker/examples
    ports:
      - 5000:5000
    environment:
      FLASK_ENV: development
